# Generated by Django 3.1.7 on 2021-03-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inet', '0003_delete_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('color', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrowSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(default='', upload_to='images/SubGrow')),
                ('description', models.TextField(null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inet.growsection')),
            ],
        ),
        migrations.CreateModel(
            name='SubSectionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/SubGrow')),
                ('description', models.TextField(null=True)),
                ('sub_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inet.growsubsection')),
            ],
        ),
    ]
