# Generated by Django 3.1.7 on 2021-03-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inet', '0004_growsection_growsubsection_subsectiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContectSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/SubGrow')),
            ],
        ),
    ]
