# Generated by Django 3.1.7 on 2021-03-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inet', '0006_auto_20210323_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContectSubSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/SubGrow')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contectsections',
            name='image',
            field=models.ImageField(default='', upload_to='images/SubGrow'),
        ),
        migrations.CreateModel(
            name='SubContectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/SubGrow')),
                ('description', models.TextField(null=True)),
                ('sub_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inet.contectsubsections')),
            ],
        ),
        migrations.AddField(
            model_name='contectsubsections',
            name='sub_section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inet.contectsections'),
        ),
    ]
