# Generated by Django 3.1.7 on 2021-03-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inet', '0008_auto_20210324_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growsection',
            old_name='color',
            new_name='background_color',
        ),
        migrations.AddField(
            model_name='growsection',
            name='text_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
