# Generated by Django 3.1.7 on 2021-03-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inet', '0009_auto_20210324_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.AddField(
            model_name='growsection',
            name='section_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inet.sectioncategory'),
        ),
    ]
