# Generated by Django 3.1.7 on 2021-03-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inet', '0012_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(null=True)),
            ],
        ),
    ]
